### ISSUE TITLE
SyntaxError if print node in opening HTML Tag

### ISSUE THREAD

**Issue by pdureau** [davidodenwald/prettier-plugin-jinja-template#19] opened 2023-08-25 13:39 UTC
Hi David,

Thank for your plugin, we are excited to add it to our workflow. However, we may have found an issue.

With this template:

```
<div {{ attributes}}>
  ...
</div>
```

I have this error

> SyntaxError: Unexpected closing tag "div". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags

This template is OK:

```
<div>
  ...
</div>
```

Is it forbidden to add Jinja code in an opening HTML Tag?

**Comment by davidodenwald** [comment] 2023-08-30 20:06
I tried to reproduce the issue but i could not. What i did:

```bash
mkdir prettier-test
cd prettier-test
npm install --save-dev prettier prettier-plugin-jinja-template
echo '{ "plugins": ["prettier-plugin-jinja-template"] }' > .prettierrc
echo "<div {{ attributes}}>
  ...
</div>" > test.jinja
npx prettier test.jinja
```

Which gave me the result:
```html
<div {{ attributes }}>...</div>
```
and no error.

Please provide steps to reproduce the issue.

**Comment by pdureau** [comment] 2023-08-31 08:10
Hi David,

Thanks for your answer. Here is a test.

```
$ npx prettier --version
3.0.2
$ cat test-ok.jinja 
<h1>{{ title }}</h1>
$ npx prettier --plugin=prettier-plugin-jinja-template test-ok.jinja 
<h1>{{ title }}</h1>
$ cat test-ko.jinja 
<h{{ heading_level }}>{{ title }}</h{{ heading_level }}>
$ npx prettier --plugin=prettier-plugin-jinja-template test-ko.jinja 
test-ko.jinja
[error] test-ko.jinja: SyntaxError: Unexpected closing tag "h#~3~#". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (1:14)
[error] > 1 | <h#~1~#>#~2~#</h#~3~#>
[error]     |              ^^^^^^^^^
[error]   2 |
```

**Comment by davidodenwald** [comment] 2023-09-04 12:13
**This plugin doesn't support syntax where part of the HTML element is a Jinja expression.**

This plugin works by replacing Jinja syntax with placeholders like `#~1~#`. The result gets formatted by the default HTML formatter and then the Jinja parts are put back into the syntax tree.

Because the HTML formattes sees this as its input:
```
<h#~1~#>#~2~#</h#~3~#>
```
tt raises the `Unexpected closing tag "h#~3~#".` error.

**Closed by davidodenwald** 2023-09-04 12:13 UTC
